version: 2.1
orbs:
  ruby: circleci/ruby@1.7.1
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.0
    steps:
      - checkout
      - ruby/install-deps
  test:
    parallelism: 1
    docker:
      - image: cimg/ruby:2.7.0
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: space_stone_test
          MYSQL_USER: root
          MYSQL_PASSWORD: password
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci-demo-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - run:
          name: default mysql client install
          command: |
            sudo apt update
            sudo apt-get install default-mysql-client
            sudo apt-get install libmysqlclient-dev
      - checkout
      - ruby/install-deps
      
      - run:
          name: DB の待機
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: データベースのセットアップ
          command: bundle exec rails db:schema:load --trace
          # RSpec を並列実行します。
      - ruby/rspec-test

workflows:
  version: 2
  build_and_test:     # ワークフローの名前は "build_and_test" です。
    jobs:             # このワークフローの一部として実行するジョブのリストです。
      - build         # まず、ビルドを実行します。
      - test:         # 次に、テストを実行します。
          requires:   # テストを実行するにはビルドを渡す必要があります。
            - build  

