version: '2.1'
orbs:
  ruby: circleci/ruby@1.7.1
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.0
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_HOST: '%'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          # MYSQL_HOST: 'db'
        command: mysqld --default-authentication-plugin=mysql_native_password
    steps:
      - checkout
      - run:
          name: default mysql client install
          command: |
            sudo apt update -qq
            sudo apt-get install -y default-mysql-client
            sudo apt-get install -y libmysqlclient-dev
      - ruby/install-deps
  test:
    docker:
      - image: cimg/ruby:2.7.0
        environment:
          RAILS_ENV: 'test'
          DB_HOST: 127.0.0.1
          DB_USERNAME: 'root'
          DB_PASSWORD: ''
      - image: cimg/mysql:8.0
        environment:
          # MYSQL_DATABASE: space_stone_test
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_HOST: '%'
          # MYSQL_USER: root
          # MYSQL_PORT: 3306
        command: mysqld --default-authentication-plugin=mysql_native_password
    parallelism: 3
    steps:
      - checkout
      - run: mv config/database.yml.ci config/database.yml
      - run:
          name: default mysql client install
          command: |
            sudo apt update -qq
            sudo apt-get install -y default-mysql-client
            sudo apt-get install -y libmysqlclient-dev
      - run:
          name: RUN apt install tzdata
          command: sudo apt-get install -y tzdata
      - ruby/install-deps
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - ruby/rspec-test
workflows:
  build_and_test:
    jobs:
      - build
      # - checking
      - test:
          requires:
            - build